name: Build and Deploy to Azure DEV

on:
    push:
        branches:
            - "dev"
    workflow_dispatch:

jobs:
    build:
        runs-on: ecz-vm-panda-dev-gwc-01
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Azure Container Registry
              run: |
                  az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile.devenv
                  push: true
                  tags: |
                      ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/panda-api:${{ github.sha }}
                      ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/panda-api:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            # TODO: Add Azure Container Apps deployment
